spring:
  application:
    name: notification-sender
  mail:
    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
          starttls:
            enable: true
  kafka:
    #      Este serviço assume semântica at-least-once.
    #      Mensagens podem ser reprocessadas em caso de falha.
    #      Duplicidade é tratada por processedEmailEventService usando eventId + eventType.
    admin:
      auto-create: ${KAFKA_AUTO_CREATE_TOPICS}
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: ${GROUP_ID}
      auto-offset-reset: ${KAFKA_AUTO_OFFSET_RESET:latest}
      enable-auto-commit: ${KAFKA_ENABLE_AUTO_COMMIT:false}
    listener:
      ack-mode: ${KAFKA_ACK_MODE:record}
      concurrency: ${KAFKA_CONCURRENCY:1}

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    default-schema: public
    liquibase-schema: public
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  jpa:
    open-in-view: false

server:
  port: ${SERVER_PORT:8080}

app:
  mail:
    # NOTIFICATION_MAIL_FROM = Username personalizado que aparece no email enviado
    from: ${NOTIFICATION_MAIL_FROM:${SPRING_MAIL_HOST}}
  kafka:
    topico-envio-email: ${TOPICO_ENVIO_EMAIL}
    topico-envio-email-dlq: ${TOPICO_ENVIO_EMAIL_DLQ}