spring:
  mail:
    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
    version: openapi_3_0
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    url: /api-docs
app:
  security:
    x-api-key: ${X_API_KEY}