<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>br.dev.leoduarte</groupId>
        <artifactId>notification-sender</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>notification-sender-service</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>jar</packaging>

    <properties>
        <!-- ===================================================================== -->
        <!-- =============== Personal properties and Local configs =============== -->
        <!-- ===================================================================== -->

        <scm-provider>git</scm-provider>
        <scm-url>https://github.com</scm-url>
        <repository-name>${project.name}</repository-name>
        <ssh-scm-connection>git@github.com</ssh-scm-connection>
        <scm-username>${settings-xml.scm-username}</scm-username>

        <registry-port>443</registry-port>
        <registry-protocol>https</registry-protocol>
        <registry-host>registry.leoduarte.dev.br</registry-host>
        <repository-path>nexus/content/repositories</repository-path>
        <repository-releases.name>nexus-maven-releases</repository-releases.name>
        <repository-snapshots.name>nexus-maven-snapshots</repository-snapshots.name>

        <!-- ===================================================================== -->
        <!-- =============================== Build =============================== -->
        <!-- ===================================================================== -->

        <encoding>UTF-8</encoding>
        <java.version>21</java.version>

        <project.build.os>unknown</project.build.os>
        <project.build.arch>x86_64</project.build.arch>
        <project.build.indentSize>4</project.build.indentSize>
        <project.build.lineLength>160</project.build.lineLength>
        <project.reporting.source>${encoding}</project.reporting.source>
        <project.build.sourceEncoding>${encoding}</project.build.sourceEncoding>
        <project.reporting.outputEncoding>${encoding}</project.reporting.outputEncoding>

        <skipITs>true</skipITs>

        <maven.deploy.only>false</maven.deploy.only>
        <maven.build.indentSize>4</maven.build.indentSize>
        <maven.compiler.parameters>true</maven.compiler.parameters>
        <maven.compiler.source>${java.version}</maven.compiler.source>
        <maven.compiler.target>${java.version}</maven.compiler.target>
        <maven.compiler.release>${java.version}</maven.compiler.release>
        <maven.compiler.showWarnings>true</maven.compiler.showWarnings>
        <maven.compiler.failOnWarning>false</maven.compiler.failOnWarning>
        <maven.compiler.showDeprecation>true</maven.compiler.showDeprecation>

        <frontend-maven-plugin.version>1.15.4</frontend-maven-plugin.version>
        <jacoco-maven-plugin.version>0.8.15</jacoco-maven-plugin.version>

        <!-- ===================================================================== -->
        <!-- ============================= Docker ================================ -->
        <!-- ===================================================================== -->

        <docker.verbose>true</docker.verbose>
        <docker.tag>${project.version}</docker.tag>
        <docker.final.name>
            ${dockerhub.username}/${project.artifactId}:${docker.tag}
        </docker.final.name>

        <!-- ===================================================================== -->
        <!-- ============================ Libraries ============================== -->
        <!-- ===================================================================== -->

        <notification-sender-spec.version>0.0.1-SNAPSHOT</notification-sender-spec.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>br.dev.leoduarte</groupId>
            <artifactId>notification-sender-spec</artifactId>
            <version>${notification-sender-spec.version}</version>
            <scope>compile</scope>
        </dependency>

        <!-- Springboot Managed Dependencies-->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-mail</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.retry</groupId>
            <artifactId>spring-retry</artifactId>
            <version>${spring-retry.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.kafka</groupId>
            <artifactId>spring-kafka</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-kafka</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webmvc</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-liquibase</artifactId>
        </dependency>

        <!-- Outras dependencias -->
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct</artifactId>
            <version>${mapstruct.version}</version>
        </dependency>
        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct-processor</artifactId>
            <version>${mapstruct.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.liquibase</groupId>
            <artifactId>liquibase-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
        </dependency>

        <!-- Dependencias de teste -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-kafka-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webmvc-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.restdocs</groupId>
            <artifactId>spring-restdocs-mockmvc</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <profiles>
        <profile>
            <id>docker-build-push</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.springframework.boot</groupId>
                        <artifactId>spring-boot-maven-plugin</artifactId>
                        <version>${project.parent.parent.version}</version>
                        <executions>
                            <execution>
                                <id>spring-image</id>
                                <goals>
                                    <goal>build-image</goal>
                                </goals>
                                <configuration>
                                    <layers>
                                        <enabled>true</enabled>
                                    </layers>
                                    <image>
                                        <name>${docker.final.name}</name>
                                        <publish>true</publish>
                                    </image>
                                    <docker>
                                        <publishRegistry>
                                            <username>${dockerhub.username}</username>
                                            <password>${dockerhub.password}</password>
                                            <url>${dockerhub.registry}</url>
                                            <email>${dockerhub.email}</email>
                                        </publishRegistry>
                                    </docker>
                                    <imageBuilder>docker.io/paketobuildpacks/builder-jammy-java-tiny:latest
                                    </imageBuilder>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>

    <scm>
        <connection>scm:${scm-provider}:${scm-url}/${scm-username}/${repository-name}.git</connection>
        <developerConnection>
            scm:${scm-provider}:${ssh-scm-connection}:${scm-username}/${repository-name}.git
        </developerConnection>
        <url>${scm-url}/${scm-username}/${repository-name}</url>
        <tag>condominio-backend-0.0.1</tag>
    </scm>

    <issueManagement>
        <system>Github</system>
        <url>${scm-url}/${scm-username}/${repository-name}/issues</url>
    </issueManagement>

    <distributionManagement>
        <repository>
            <id>nexus-maven-releases</id>
            <name>Maven Hosted Releases Repository</name>
            <url>
                ${registry-protocol}://${registry-host}:${registry-port}/${repository-path}/${repository-releases.name}/
            </url>
        </repository>
        <snapshotRepository>
            <id>nexus-maven-snapshots</id>
            <name>Maven Hosted Snapshots Repository</name>
            <url>
                ${registry-protocol}://${registry-host}:${registry-port}/${repository-path}/${repository-snapshots.name}/
            </url>
        </snapshotRepository>
    </distributionManagement>
</project>
